### PR TITLE
Update to component/theme v6 syntax

### LINKED ISSUE #38: Routing template missing drawer navigation in new project
#### Describe the bug
On a new RN routing project spun up via latest "npx -p @pxblue/cli" has missing drawer navigation / icon

image

#### What is the expected behavior?
Drawer nav to be available and navs to page 1 & 2
#### What are the steps to reproduce?
1. open new terminal and run npx -p @pxblue/cli > react-native > routing
2. cd ios > pod install
3. run android/ios

### PR DESCRIPTION
**Pull request by joebochill**
Fixes #38 

#### Changes proposed in this Pull Request:
- Update to use the new icon syntax where appropriate\

#### To Test:
- Follow the instructions in the Readme for testing template files locally
- I tested the auth typescript template locally and used that to propagate changes to the other templates, so I did not explicitly test the others. It would be good to just run through and make sure they all work.

**NOTE**: This PR depends on @pxblue/react-native-components@6.0.1 and @pxblue/react-native-auth-workflow@4.0.0 being published. We should update the packager versions in dependencies.json once they are available to replace the betas currently specified therein.

### CODE REVIEW

**Comment by daileytj** [comment]
Once this is merged, we can also call PXBLUE-2602 in JIRA done... or close it.

**Comment by joebochill** [comment]
The demo project should run now...had to install the new required dependencies and apply the xCode 12.5 workaround.

**Comment by joebochill** [comment]
> Should the contact support and reset password pages have a back button?

I believe for RN they have a close button in the header instead of a back button in the footer.

**Comment by joebochill** [comment]
Almost done with the workflow updates...but they are going to necessitate another patch for the component library as well to fix this: https://github.com/pxblue/react-native-component-library/issues/213

**Comment by daileytj** [comment]
Ahh, was just looking at this @jeffvg. That's that `react-native-keyboard-aware-scroll-view` we've seen before. I can't recall what we did to fix it though. I'll look into it more and see what we can do.

**Comment by daileytj** [comment]
The JS project template is using latest RN v0.66 while the TS version is using 64.1, we fixed it for TS and locked that down in the cl... I'll see if I can find where the js version is being set and make sure we lock that down too.

**Comment by daileytj** [comment]
@jeffvg can you list out which version of react-native each of the test projects you spun are using?

**Comment by daileytj** [comment]
https://github.com/pxblue/pxblue-cli/pull/107 I have this in the works to try to lock down RN to 0.64, but not getting it just right yet.

**Comment by jeffvg** [comment]
> [pxblue/pxblue-cli#107](https://github.com/pxblue/pxblue-cli/pull/107) I have this in the works to try to lock down RN to 0.64, but not getting it just right yet.

The type-script templates using 0.64.1
The java-script templates using 0.66.1

**Comment by daileytj** [comment]
https://github.com/pxblue/pxblue-cli/pull/107 should be ready to go and will lock down the version to RN 64.

**Review by jeffvg — APPROVED** [review]
looks good now using RN 64.1. Just need to update change log date

**Pull request merged**
