### PR TITLE
update blank temp to use SafeAreaProvider

### PR DESCRIPTION
**Pull request by jeffvg**
Fixes #99 https://github.com/pxblue/pxblue-cli/issues/99

#### Changes proposed in this Pull Request:
- update both blank templates to use SafeAreaProvider
- 
- 

#### To Test:
-

### CODE REVIEW

**Comment by joebochill** [comment]
Why are we only doing this for the blank templates? And did we attempt the preferred solution of putting the provider in the header component?

**Comment by jeffvg** [comment]
> Why are we only doing this for the blank templates? And did we attempt the preferred solution of putting the provider in the header component?

Both the blank templates apps we built use SafeAreaView and needed the SafeAreaProvider with it. The other template app files are not using SafeAreaView.

We can definitely just move it in to RN component library but think the apps in the blank templates will still need to render out both SafeAreaView and SafeAreaPrivider

**Comment by joebochill** [comment]
Interesting. I thought the tests were failing because of the usesafeareainsets hook in the header component. Is the default test passing for the other templates?

**Comment by jeffvg** [comment]
> Interesting. I thought the tests were failing because of the usesafeareainsets hook in the header component. Is the default test passing for the other templates?

yes the other templates tests pass

**Comment by jeffvg** [comment]
> Interesting. I thought the tests were failing because of the usesafeareainsets hook in the header component. Is the default test passing for the other templates?

working with @daileytj  later to look at adding safe area provider to the React Native Header component in the RN repo later today

**Comment by daileytj** [comment]
Not going to approve yet as this may need more discussion, but if we decide this is the way to go I'm happy with the current state of this. There may be a better way to handle this, but right now it doesn't seem as if adding the `SafeAreaProvider` to the `Header` is going to work to fix this issue.

**Comment by joebochill** [comment]
It does seem that according to the docs, using the provider at the app root is the recommended way to go: https://github.com/th3rdwave/react-native-safe-area-context#safeareaprovider

If adding it to the Header doesn't fix the issue, then let's not do that / take it out since it could potentially cause conflicts and instead just add a blurb to the Header docs / readme that says you should make sure you have the Provider at the top of your app when you are using it.

**Comment by joebochill** [comment]
This looks good, let's just add the Provider on all of the other templates too to future proof them.

**Review by joebochill — APPROVED** [review]

**Pull request merged**
