### PR TITLE
Feature/2505 blui

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
-  GO BLUI

### CODE REVIEW

**Comment by emclaug2** [comment]
I tested this on android, but not ios yet.

**Comment by daileytj** [comment]
Code looks good, I'll test it out with CLI and iOS tomorrow

**Comment by emclaug2** [comment]
I tested this on IOS this morning, after running pod install, it all worked.

**Comment by jeffvg** [comment]
@emclaug2 looking at this now

**Comment by jeffvg** [comment]
should all the dependencies.json be updated as well for this PR?

image

**Comment by emclaug2** [comment]
@jeffvg @daileytj I think I caught all the missed references now.

**Review by daileytj — APPROVED** [review]
Looks good to me. Will need to test these again after cli is updated but I made the changes locally and it should all work out in the end.

**Pull request merged**
